### ISSUE TITLE
Tables Not Render

### ISSUE THREAD

**Issue by ibitcat** [nathancday/min_night#2]
Firstly, thanks for the awesome theme! 

But there may be some problems when rendering the table.they both get rendered without any table lines.

**Comment by nathancday** [comment]
Can you provide a small example of the table code to reproduce the issue?
Maybe a screenshot too to show it. You don’t have to do that all here, just
links to available files.

I haven’t used any tables yet myself. So I’m not surprised the lines seem
to be missing. Likely something in the CSS, but we will figure it out.

**Comment by ibitcat** [comment]
ok, examples of tables are as follows:

~~~
| Header1 | Header2 | Header3 |
|:--------|:-------:|--------:|
| cell1   | cell2   | cell3   |
| cell4   | cell5   | cell6   |
~~~

screenshot:
![image](https://user-images.githubusercontent.com/3291453/43202685-b20deece-904e-11e8-81d2-d311cdbd6d38.png)

![image](https://user-images.githubusercontent.com/3291453/43202859-2dd95f16-904f-11e8-8b74-de8af6f3ea31.png)

**Comment by nathancday** [comment]
I think you pretty much solved the problem, the theme's CSS isn't set up to give the borders you want by default.

So in Hugo-land you have a couple of options to get those borders back:

1. Edit the theme's CSS file in `your_site/themes/min_night/static/main.css` directly (not a great idea, unless you want to change a bunch of stuff, because updating from the theme source in the future becomes more complicated)

2. Copy the partial layout `css.html` from the theme `your_site/themes/min_night/layouts/partials/css.html` into the top level of your site `your_site/layouts/partials`. This is the preferred method. You may need to create the directory `partials`. Once you have that copied just add the following code chunk to get black borders around your tables:

```
<style>
    table, th, td {
      border: 1px solid black;
    }
</style>
```
Note the `<style>` tag becasue this is actually an HTML file. Hugo default is to overwrite the theme's layouts with any layouts it finds in `your_site/layouts` so you can customize everything!

3. Insert inline styles directly into your table html. This option is the easiest but isn't very fun once you have to repeat it. So if you want all the tables on your site to have a specific border formatting, pick #2.

If you want some more resource in table styling with CSS, [W3 schools is great](https://www.w3schools.com/css/css_table.asp).

I don't plan to change the table styling universally for the theme right now, but would consider doing so if enough people want to always have the borders.

I'll leave this issue open until you confirm that you are getting your borders. Cheers :)

**Comment by ibitcat** [comment]
The table can now be rendered properly. thank you very much for your advice. 👍
