### ISSUE TITLE
Update to support Hugo 0.35

### ISSUE THREAD

**Issue by asachs01** [nathancday/min_night#3]
When running Hugo, I receive the error: 

`ERROR 2018/10/29 16:46:17 Current theme does not support Hugo version 0.34. Minimum version required is 0.35`

Would it be possible to bump up the supported version?

**Comment by asachs01** [comment]
Erp. NVM. This was a bit of PEBKAC. However, I'm not seeing anything render when using a later version of hugo (I'm on 0.50).

**Comment by asachs01** [comment]
Ah, found the issue. The command you have under the installation in the Readme is dumping things to a new dir `exampleSite`, not actually creating dummy content. `cp -r themes/min_night/exampleSite/* .` should do the trick.

**Comment by nathancday** [comment]
Hi @asachs01, what shell are you using? Also do you see an error messages or does Hugo seem to fire up and run okay?

The README code is written in bash and works well for me on both Hugo v0.35 and v0.50. No new folders should be be created by copying the exampleSite, the folder structure is set by `hugo new site quick`. But new files will be created into the existing directories.

The code you suggested `cp -r themes/min_night/exampleSite/* .` throws an error on my machine for `cp usage`, because `cp` is expecting a target path to a file or directory, ie no wild cards. The `-r` flag is already handling the recursive copying of all content below the target directory.
